services:

  # =========================
  # PostgreSQL Database
  # =========================
  postgres:
    image: postgres:18.6
    container_name: cryptune-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: cryptune
      POSTGRES_USER: cryptune
      POSTGRES_PASSWORD: cryptune_password

    volumes:
      - cryptune-postgres-data:/var/lib/postgresql

    networks:
      - cryptune-network


  # =========================
  # Backend
  # =========================
  backend:
    image: cryptune-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: cryptune-backend
    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "4000:4000"

    depends_on:
      - postgres

    networks:
      - cryptune-network


  # =========================
  # Frontend
  # =========================
  frontend:
    image: cryptune-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: cryptune-frontend
    restart: unless-stopped

    ports:
      - "5173:80"

    depends_on:
      - backend

    networks:
      - cryptune-network


# =========================
# Persistent Database Volume
# =========================
volumes:
  cryptune-postgres-data:
    name: cryptune-postgres-data


# =========================
# Docker Network
# =========================
networks:
  cryptune-network:
    name: cryptune-network
